apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.app.name }}
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.app.name }}-app
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            args: 
            {{- range .Values.app.args }}
              - {{ . -}}
            {{ end }}
            {{- with .Values.app.env }}
            env:
              {{- toYaml . | nindent 12 }}
            {{- end }}
          restartPolicy: Never