apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.app.name }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.app.name }}-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args: 
        {{- range .Values.app.args }}
          - {{ . -}}
        {{ end }}
        env:
        {{- range $k, $v := .Values.app.env }}
        - name: {{ $k }}
          value: {{ $v | upper -}}
        {{ end }}
      restartPolicy: Never
  backoffLimit: 1