apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.app.name }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.app.name }}-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args: 
        {{- range .Values.app.args }}
          - {{ . -}}
        {{ end }}
        {{- with .Values.app.env }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      restartPolicy: Never
  backoffLimit: 1