# Default values for ponder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/seemywingz/ponder
  pullPolicy: Always
  tag: test

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

app:
  name: ponder
  args:
    - discord-bot
    - -v
  configData:
    openAI_endpoint: "https://api.openai.com/v1/"
    openAI_image_size: "1024x1024"
    openAI_image_downloadPath: "~/Ponder/Images"
    openAI_chat_topP: "0.1"
    openAI_chat_temperature: "0"
    openAI_chat_maxTokens: "999"
    openAI_chat_presencePenalty: "0.6"
    openAI_chat_frequencyPenalty: "0.0"
    openAI_chat_model: "gpt-3.5-turbo"
    openAI_text_topP: "0.1"
    openAI_text_temperature: "0"
    openAI_text_maxTokens: "999"
    openAI_text_presencePenalty: "0.6"
    openAI_text_frequencyPenalty: "0.0"
    openAI_text_model: "text-davinci-003"
  env:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: openai-api-key
          key: api-key
    - name: PRINTIFY_API_KEY
      valueFrom:
        secretKeyRef:
          name: printify-api-key
          key: api-key
    - name: DISCORD_API_KEY
      valueFrom:
        secretKeyRef:
          name: discord-api-key
          key: api-key
    - name: DISCORD_PUB_KEY
      valueFrom:
        secretKeyRef:
          name: discord-pub-key
          key: pub-key

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "cloudlfare-letsencrypt-production"
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_x_auth_request_access_token;
  more_set_headers "Request-Id: $req_id";
  hosts:
    - host: discipuli.ai
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: discipuli.ai-tls
      hosts:
        - discipuli.ai

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext: {}

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
