# Default values for ponder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: disciplesofai/ponder
  pullPolicy: Always
  tag: "dev"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

app:
  name: ponder
  args:
    - api-server
    - -v
  env:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: openai-api-key
          key: api-key
    - name: ETSY_API_KEY
      valueFrom:
        secretKeyRef:
          name: etsy-api-key
          key: api-key
    - name: PRINTIFY_API_KEY
      valueFrom:
        secretKeyRef:
          name: printify-api-key
          key: api-key
    - name: DISCORD_API_KEY
      valueFrom:
        secretKeyRef:
          name: discord-api-key
          key: api-key

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    { cert-manager.io/cluster-issuer: "cloudlfare-letsencrypt-production" }
  hosts:
    - host: discipuli.ai
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: discipuli.ai-tls
      hosts:
        - discipuli.ai

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext: {}

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
