name: Docker BuildX

on:
  push:
    branches:
      - "develop"
      - "github-actions-ghcr"
    tags:
      - "**"

env:
  REGISTRY: ghcr.io
  IMAGE_VERSION: edge
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3

      - name: Docker Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Image Version
        run: |

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
            VERSION=${GITHUB_REF#refs/heads/}
          else
            VERSION=latest
          fi

          echo "IMAGE_VERSION=${VERSION}"
          echo "IMAGE_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Docker Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
